FROM openjdk:8
MAINTAINER arz
EXPOSE ${CONFIGURER_PORT:-8888}
ADD /target/mimsic-fintech-solution-design-configurer.jar /app/application.jar
ENTRYPOINT ["java", "-Xmx200m", "-jar", "/app/application.jar"]
HEALTHCHECK --interval=30s --timeout=30s CMD curl -f http://localhost:${CONFIGURER_PORT:-8888}/actuator/health || exit 1