---
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest